# Generated by Django 2.2.12 on 2021-06-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=11, verbose_name='学号')),
                ('username', models.CharField(max_length=11, verbose_name='姓名')),
                ('cet4', models.IntegerField(verbose_name='四级成绩')),
                ('cet6', models.IntegerField(verbose_name='六级成绩')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='用户创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='测试时间')),
                ('result', models.IntegerField(verbose_name='测试结果')),
            ],
        ),
    ]
